// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfjCurVTsIYuRgGbI_AqXfOYkB6Bo1AMA',
    appId: '1:91725791419:web:59d3d9fbc15de5e176e99e',
    messagingSenderId: '91725791419',
    projectId: 'estudy-11a65',
    authDomain: 'estudy-11a65.firebaseapp.com',
    storageBucket: 'estudy-11a65.firebasestorage.app',
    measurementId: 'G-4P08BDNVWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7JX4QLIyjPMjZEZF7j__95FGbgMbEzy0',
    appId: '1:91725791419:android:4e76786ca21bea8f76e99e',
    messagingSenderId: '91725791419',
    projectId: 'estudy-11a65',
    storageBucket: 'estudy-11a65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPBVtDkFHql-hCwunKXcEDZ2XkPnZCojQ',
    appId: '1:91725791419:ios:bcee1a7d0ff049bb76e99e',
    messagingSenderId: '91725791419',
    projectId: 'estudy-11a65',
    storageBucket: 'estudy-11a65.firebasestorage.app',
    iosBundleId: 'com.ppfuark.estudy',
  );
}
