// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9iSybswCmGQ4wggGJrl89-K1BTm_np7c',
    appId: '1:837625158972:web:bcd15c2f92aa1f19391239',
    messagingSenderId: '837625158972',
    projectId: 'chat-app-fuark',
    authDomain: 'chat-app-fuark.firebaseapp.com',
    storageBucket: 'chat-app-fuark.firebasestorage.app',
    measurementId: 'G-LBF3KV76QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbxBXwiy58uh50FONA8mGQRT4ZIm812VU',
    appId: '1:837625158972:android:1484a44dd28ea9f0391239',
    messagingSenderId: '837625158972',
    projectId: 'chat-app-fuark',
    storageBucket: 'chat-app-fuark.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA73d9S-ens-fonhbh1q4ADbg0N0gdG8Ds',
    appId: '1:837625158972:ios:e24fb848857c07e6391239',
    messagingSenderId: '837625158972',
    projectId: 'chat-app-fuark',
    storageBucket: 'chat-app-fuark.firebasestorage.app',
    iosBundleId: 'com.ppfuark.chatApp',
  );
}
